### ISSUE TITLE
Faraday::SSLError: SSL_connect returned=1 errno=0 state=error: certificate verify failed

### ISSUE THREAD

**Issue by monstar-taka** [inokappa/furikake#10]
`bundle exec furikake publish`を実行時にエラーとなります。
この場合、何が原因だと思いますか？

当方の実行環境は以下の通り。
```
ProductName:	Mac OS X
ProductVersion:	10.13.6
BuildVersion:	17G65
ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-darwin16]
```
お手数ですが、ご確認お願い致します。

```
bundler: failed to load command: furikake (/usr/local/github/furikake/vendor/bundle/ruby/2.4.0/bin/furikake)
Faraday::SSLError: SSL_connect returned=1 errno=0 state=error: certificate verify failed
  /Users/takachan/.rbenv/versions/2.4.1/lib/ruby/2.4.0/net/protocol.rb:44:in `connect_nonblock'
  /Users/takachan/.rbenv/versions/2.4.1/lib/ruby/2.4.0/net/protocol.rb:44:in `ssl_socket_connect'
  /Users/takachan/.rbenv/versions/2.4.1/lib/ruby/2.4.0/net/http.rb:948:in `connect'
  /Users/takachan/.rbenv/versions/2.4.1/lib/ruby/2.4.0/net/http.rb:887:in `do_start'
  /Users/takachan/.rbenv/versions/2.4.1/lib/ruby/2.4.0/net/http.rb:876:in `start'
  /Users/takachan/.rbenv/versions/2.4.1/lib/ruby/2.4.0/net/http.rb:1407:in `request'
  /usr/local/github/furikake/vendor/bundle/ruby/2.4.0/gems/faraday-0.15.3/lib/faraday/adapter/net_http.rb:87:in `perform_request'
  /usr/local/github/furikake/vendor/bundle/ruby/2.4.0/gems/faraday-0.15.3/lib/faraday/adapter/net_http.rb:43:in `block in call'
  /usr/local/github/furikake/vendor/bundle/ruby/2.4.0/gems/faraday-0.15.3/lib/faraday/adapter/net_http.rb:92:in `with_net_http_connection'
  /usr/local/github/furikake/vendor/bundle/ruby/2.4.0/gems/faraday-0.15.3/lib/faraday/adapter/net_http.rb:38:in `call'
  /usr/local/github/furikake/vendor/bundle/ruby/2.4.0/gems/faraday-0.15.3/lib/faraday/response.rb:8:in `call'
  /usr/local/github/furikake/vendor/bundle/ruby/2.4.0/gems/faraday-0.15.3/lib/faraday/response.rb:8:in `call'
  /usr/local/github/furikake/vendor/bundle/ruby/2.4.0/gems/faraday_middleware-0.12.2/lib/faraday_middleware/response_middleware.rb:31:in `call'
  /usr/local/github/furikake/vendor/bundle/ruby/2.4.0/gems/faraday-0.15.3/lib/faraday/request/url_encoded.rb:15:in `call'
  /usr/local/github/furikake/vendor/bundle/ruby/2.4.0/gems/faraday-0.15.3/lib/faraday/request/multipart.rb:15:in `call'
  /usr/local/github/furikake/vendor/bundle/ruby/2.4.0/gems/faraday-0.15.3/lib/faraday/rack_builder.rb:143:in `build_response'
  /usr/local/github/furikake/vendor/bundle/ruby/2.4.0/gems/faraday-0.15.3/lib/faraday/connection.rb:387:in `run_request'
  /usr/local/github/furikake/vendor/bundle/ruby/2.4.0/gems/faraday-0.15.3/lib/faraday/connection.rb:175:in `patch'
  /usr/local/github/furikake/vendor/bundle/ruby/2.4.0/gems/backlog_kit-0.17.0/lib/backlog_kit/client.rb:140:in `request'
  /usr/local/github/furikake/vendor/bundle/ruby/2.4.0/gems/backlog_kit-0.17.0/lib/backlog_kit/client.rb:124:in `patch'
  /usr/local/github/furikake/vendor/bundle/ruby/2.4.0/gems/backlog_kit-0.17.0/lib/backlog_kit/client/wiki.rb:55:in `update_wiki'
  /usr/local/github/furikake/lib/furikake/reporters/backlog.rb:19:in `publish'
  /usr/local/github/furikake/lib/furikake/report.rb:26:in `block in publish'
  /usr/local/github/furikake/lib/furikake/report.rb:21:in `each'
  /usr/local/github/furikake/lib/furikake/report.rb:21:in `publish'
  /usr/local/github/furikake/lib/furikake/cli.rb:19:in `publish'
  /usr/local/github/furikake/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
  /usr/local/github/furikake/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
  /usr/local/github/furikake/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
  /usr/local/github/furikake/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
  /usr/local/github/furikake/exe/furikake:5:in `<top (required)>'
  /usr/local/github/furikake/vendor/bundle/ruby/2.4.0/bin/furikake:22:in `load'
  /usr/local/github/furikake/vendor/bundle/ruby/2.4.0/bin/furikake:22:in `<top (required)>'
```

**Comment by inokappa** [comment]
フィードバックありがとうございます！
確認いたします.

**Comment by inokappa** [comment]
@monstar-taka 

フィードバックありがとうございます！
以下, お試し頂けますでしょうか.

```
$ pwd
path/to/furikake
$ wget http://curl.haxx.se/ca/cacert.pem
$ ls -l cacert.pem
$ SSL_CERT_FILE=cacert.pem bundle exec furikake publish
```

よろしくお願いいたします.

**Comment by monstar-taka** [comment]
@inokappa 
環境依存の問題を疑ったので、EC2インスタンスを作成してその上で実施しましたが同様の事象が発生しました。

```
[ec2-user@ip-172-31-43-138 furikake]$ ruby -ropenssl -e "p OpenSSL::X509::DEFAULT_CERT_FILE"
"/etc/pki/tls/cert.pem"

[ec2-user@ip-172-31-43-138 furikake]$ SSL_CERT_FILE=/etc/pki/tls/cert.pem bundle exec furikake publish
bundler: failed to load command: furikake (/home/ec2-user/furikake/vendor/bundle/ruby/2.5.0/bin/furikake)
Faraday::SSLError: SSL_connect returned=1 errno=0 state=error: certificate verify failed (error number 1)
```

**Comment by inokappa** [comment]
@monstar-taka 

検証ありがとうございます！！！！
Amazon Linux のバージョン, Ruby バージョンも合わせて共有をお願い致します. 🙇 

また, Ruby Gems でも公開いたしました. (https://rubygems.org/gems/furikake)
よろしければ, `gem install furikake` 等でお試し下さい :bow:

**Comment by inokappa** [comment]
@monstar-taka 

度々のご連絡となりすいません！

furikake を docker で動かせるようにしてみました (https://github.com/inokappa/furikake-docker) もし, どうしても Mac 上で動かないようでしたら, furikake-docker でお試し下さい :bow:

**Comment by Twinuma** [comment]
@inokappa おぉぉ、ありがとうございます！！！！試してみます！！！

**Comment by inokappa** [comment]
稼働の確認が取れましたので本 issue は close します〜
